using System;

namespace Standard
{
	internal enum DWMWA
	{
		NCRENDERING_ENABLED = 1,
		NCRENDERING_POLICY = 2,
		TRANSITIONS_FORCEDISABLED = 3,
		ALLOW_NCPAINT = 4,
		CAPTION_BUTTON_BOUNDS = 5,
		NONCLIENT_RTL_LAYOUT = 6,
		FORCE_ICONIC_REPRESENTATION = 7,
		FLIP3D_POLICY = 8,
		EXTENDED_FRAME_BOUNDS = 9,
		HAS_ICONIC_BITMAP = 10,
		DISALLOW_PEEK = 11,
		EXCLUDED_FROM_PEEK = 12
	}
}